version: "3.9"
services:
  web:
    image: infracloudio/csvserver:latest
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
