version: "3.9"
services:
  web:
    image: infracloudio/csvserver:latest
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
  metrics:
    image: prom/prometheus:v2.22.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
